name: build-and-test

on:
  push:
    branches: [ main, prerelease ]
  pull_request:
    branches: [ main, prerelease ] 

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Used later for calculating GitVersion

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Build Docker Image
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-build
        tags: gaip-net/build:latest
    
    - name: Run tests
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-test
        tags: test-results:latest
        load: true
        
    - name: Copy test results
      run: |
        id=$(docker create test-results)
        docker cp $id:/work/testresults ${{ github.workspace }}/testresults
      
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ${{ github.workspace }}/testresults
      if: ${{ always() }}
      
    # Build and push packages           
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
    
    - uses: docker/build-push-action@v2.9.0
      id: package
      name: Prepare packages
      with:
        file: .github/workflows/build.Dockerfile
        target: export-packages
        build-args: Version=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
        outputs: type=local,dest=${{ github.workspace }}

    - name: Upload nupkg files
      if: steps.package.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: ${{ github.workspace }}/nupkgs

      # Only push on actual builds, not on PRs
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      if: steps.package.outcome == 'success' && github.event_name != 'pull_request'
      with:
        dotnet-version: |
          6.0.x

    - name: Push to Nuget
      if: steps.package.outcome == 'success' && github.event_name != 'pull_request'
      run: |
        dotnet nuget push ${{ github.workspace }}/nupkgs/*.nupkg -k ${{ secrets.NUGET_PAT }} -s https://api.nuget.org/v3/index.json