name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Build Docker Image
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-build
        
    - name: Run tests
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-test
        tag: test-results
        
    - name: Copy test results
      uses: actions/github-script@v6.0.0
      with:
        # The script to run
        script: |
          id=$(docker create test-results) && \
          docker cp $id:/work/testresults .
          
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.2.0
      id: trx-parser
      with:
        TRX_PATH: ${{ github.workspace }}/testresults 