name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Build Docker Image
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-build
        
    - name: Run tests
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-test