name: deploy-packages

on:
  workflow_run:
    workflows: ['build-and-test']
    types:
      - completed
#    branches:
#      - main
    
jobs:
  deploy:
    name: Create and deploy packages
    runs-on: ubuntu-latest
    steps:     
    - name: Checkout build artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: gaip-net-build
        path: /tmp/gaip-net-build.tar
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    
    - name: Load Docker image
      run: |
        docker load --input /tmp/gaip-net-build.tar
          
    - name: Create and Push packages
      uses: docker/build-push-action@v2.9.0
      with:
        file: .github/workflows/build.Dockerfile
        target: dotnet-push
        tags: gaip-net/packages:latest
        build-args: Version=0.0.1-alpha # For now, hardcode the version