name: publish-test

on:
  workflow_run:
    workflows: ['build-and-test']
    types:
      - completed

jobs:
  build:
    name: Publish test run
    runs-on: ubuntu-latest
    steps:
    - name: Publish test results 
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Published test results
        path: '*.trx'
        reporter: dotnet-trx
